import { simpleGit, SimpleGit } from 'simple-git';
import { promises as fs } from 'fs';
import { join } from 'path';
import { tmpdir } from 'os';
import { randomUUID } from 'crypto';

export class GitService {
  async cloneRepository(repositoryUrl: string, branch: string): Promise<string> {
    const workDir = join(tmpdir(), `moaa-${randomUUID()}`);
    await fs.mkdir(workDir, { recursive: true });

    const git: SimpleGit = simpleGit();
    await git.clone(repositoryUrl, workDir, ['--branch', branch, '--single-branch', '--depth', '1']);

    return workDir;
  }

  async getRelevantFiles(workDir: string): Promise<Map<string, string>> {
    const files = new Map<string, string>();

    const codeExtensions = [
      '.ts', '.tsx', '.js', '.jsx', '.json', '.prisma',
      '.css', '.scss', '.html', '.md', '.yaml', '.yml',
    ];

    const ignoreDirs = ['node_modules', '.git', 'dist', 'build', '.next', 'coverage'];

    await this.walkDirectory(workDir, workDir, files, codeExtensions, ignoreDirs);

    return files;
  }

  private async walkDirectory(
    baseDir: string,
    currentDir: string,
    files: Map<string, string>,
    extensions: string[],
    ignoreDirs: string[]
  ): Promise<void> {
    const entries = await fs.readdir(currentDir, { withFileTypes: true });

    for (const entry of entries) {
      const fullPath = join(currentDir, entry.name);
      const relativePath = fullPath.replace(baseDir + '/', '');

      if (entry.isDirectory()) {
        if (!ignoreDirs.includes(entry.name)) {
          await this.walkDirectory(baseDir, fullPath, files, extensions, ignoreDirs);
        }
      } else if (entry.isFile()) {
        const hasValidExtension = extensions.some((ext) => entry.name.endsWith(ext));
        if (hasValidExtension) {
          try {
            const content = await fs.readFile(fullPath, 'utf-8');
            if (content.length < 50000) {
              files.set(relativePath, content);
            }
          } catch {
            // Skip files that can't be read
          }
        }
      }
    }
  }

  async createBranchAndApplyDiff(
    workDir: string,
    branchName: string,
    diff: string
  ): Promise<void> {
    const git: SimpleGit = simpleGit(workDir);

    await git.checkoutLocalBranch(branchName);

    const diffPath = join(workDir, '.moaa-diff.patch');
    await fs.writeFile(diffPath, diff);

    try {
      await git.raw(['apply', '--check', diffPath]);
      await git.raw(['apply', diffPath]);
    } finally {
      await fs.unlink(diffPath).catch(() => {});
    }

    await git.add('.');
    await git.commit(`feat: AI-generated change\n\nGenerated by MOAA`);
  }

  async pushBranch(workDir: string, branchName: string): Promise<void> {
    const git: SimpleGit = simpleGit(workDir);
    await git.push('origin', branchName, ['--set-upstream']);
  }

  async cleanup(workDir: string): Promise<void> {
    try {
      await fs.rm(workDir, { recursive: true, force: true });
    } catch {
      // Ignore cleanup errors
    }
  }
}
